# Generated by Django 5.0.6 on 2024-05-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0003_department_userinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(max_length=64, null=True),
        ),
    ]
